name: Deploy to Hugging Face Space

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        lfs: true
    
    - name: Push to Hugging Face Space
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        git config --global user.email "nehalecky@gmail.com"
        git config --global user.name "nehalecky"
        git config --global credential.helper ""
        git remote add space https://nehalecky:$HF_TOKEN@huggingface.co/spaces/nehalecky/First_agent_template
        git push --force space main